apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  annotations:
    app.gitlab.com/app: __CI_PROJECT_PATH_SLUG__
    app.gitlab.com/env: __CI_ENVIRONMENT_SLUG__
  labels:
    app: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
      annotations:
        app.gitlab.com/app: __CI_PROJECT_PATH_SLUG__
        app.gitlab.com/env: __CI_ENVIRONMENT_SLUG__
    spec:
      containers:
      - name: angular
        image: gitlab.lrz.de:5005/swe2_ss2021/gruppe02/website:__CI_COMMIT_SHA__
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
      imagePullSecrets:
      - name: image-pull-secret

---

apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: angular
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: angular-ingress
  annotations:
    cert-manager.io/cluster-issuer: http-fh-issuer
    kubernetes.io/ingress.class: "public"
spec:
  tls:
  - hosts:
    - __URL__
    secretName: tls-certificate
  rules:
  - host: __URL__
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: angular-service
            port:
              number: 80