/**
 * Digitaler Reiseführer
 * REST Api für den digitalen Reiseführer.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package edu.hm.digitaltourguide.api.apis


import edu.hm.digitaltourguide.api.infrastructure.*
import io.swagger.client.infrastructure.*

class PromotedApi(basePath: String = "https://SERVER/v2") : ApiClient(basePath) {

    /**
     * Get all promoted pois in an area
     * 
     * @param longitudeMin  
     * @param latitudeMin  
     * @param longitudeMax  
     * @param latitudeMax  
     * @return kotlin.Array<kotlin.Int>
     */
    @Suppress("UNCHECKED_CAST")
    fun getPromotedPOIS(longitudeMin: java.math.BigDecimal, latitudeMin: java.math.BigDecimal, longitudeMax: java.math.BigDecimal, latitudeMax: java.math.BigDecimal): Array<Int> {
        val localVariableQuery: MultiValueMap = mapOf("longitudeMin" to listOf("$longitudeMin"), "latitudeMin" to listOf("$latitudeMin"), "longitudeMax" to listOf("$longitudeMax"), "latitudeMax" to listOf("$latitudeMax"))
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/promoted", query = localVariableQuery
        )
        val response = request<Array<Int>>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as Array<Int>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
