/**
 * Digitaler Reiseführer
 * REST Api für den digitalen Reiseführer.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package edu.hm.digitaltourguide.api.apis

import edu.hm.digitaltourguide.api.infrastructure.*
import edu.hm.digitaltourguide.api.models.PostRoute
import edu.hm.digitaltourguide.api.models.Route

import io.swagger.client.infrastructure.*

class RouteApi(basePath: String = "https://SERVER/v2") : ApiClient(basePath) {

    /**
     * Add a new route to the database
     * 
     * @param body  
     * @return void
     */
    fun addRoute(body: PostRoute) {
        val localVariableBody: Any = body
        
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/route"
        )
        val response = request<Any?>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * Deletes the route to a given id
     * 
     * @param routeID  
     * @return void
     */
    fun deleteRoute(routeID: Int) {
        
        val localVariableConfig = RequestConfig(
                RequestMethod.DELETE,
                "/route/{routeID}".replace("{" + "routeID" + "}", "$routeID")
        )
        val response = request<Any?>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * Gets the route to a given id
     * 
     * @param routeID  
     * @return Route
     */
    @Suppress("UNCHECKED_CAST")
    fun getRoute(routeID: Int): Route {
        
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/route/{routeID}".replace("{" + "routeID" + "}", "$routeID")
        )
        val response = request<Route>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as Route
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * Get all routes from the given user
     * 
     * @param userName  
     * @return kotlin.Array<kotlin.Int>
     */
    @Suppress("UNCHECKED_CAST")
    fun getRoutes(userName: String): Array<Int> {
        
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/routes/{userName}".replace("{" + "userName" + "}", userName)
        )
        val response = request<Array<Int>>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as Array<Int>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * Edits the route to a given id
     * 
     * @param body  
     * @param routeID  
     * @return void
     */
    fun putRoute(body: PostRoute, routeID: Int) {
        val localVariableBody: Any = body
        
        val localVariableConfig = RequestConfig(
                RequestMethod.PUT,
                "/route/{routeID}".replace("{" + "routeID" + "}", "$routeID")
        )
        val response = request<Any?>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
