apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  annotations:
    app.gitlab.com/app: __CI_PROJECT_PATH_SLUG__
    app.gitlab.com/env: __CI_ENVIRONMENT_SLUG__
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        app.gitlab.com/app: __CI_PROJECT_PATH_SLUG__
        app.gitlab.com/env: __CI_ENVIRONMENT_SLUG__
    spec:
      containers:
      - name: api
        image: gitlab.lrz.de:5005/swe2_ss2021/gruppe02/api:__CI_COMMIT_SHA__
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__MariaDbConnectionString
          value: 'server=api-db-service; user=api; password=Gruppe02; database=api'
      imagePullSecrets:
      - name: image-pull-secret

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    cert-manager.io/cluster-issuer: http-fh-issuer
    kubernetes.io/ingress.class: "public"
spec:
  tls:
  - hosts:
    - __URL__
    secretName: tls-certificate
  rules:
  - host: __URL__
    http:
      paths:
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-db-deployment
  annotations:
    app.gitlab.com/app: __CI_PROJECT_PATH_SLUG__
    app.gitlab.com/env: __CI_ENVIRONMENT_SLUG__
  labels:
    app: api-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-db
  template:
    metadata:
      labels:
        app: api-db
      annotations:
        app.gitlab.com/app: __CI_PROJECT_PATH_SLUG__
        app.gitlab.com/env: __CI_ENVIRONMENT_SLUG__
    spec:
      containers:
      - name: api-db
        image: mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: Gruppe02
        - name: MARIADB_PASSWORD
          value: Gruppe02
        - name: MARIADB_USER
          value: api
        - name: MARIADB_DATABASE
          value: api

---

apiVersion: v1
kind: Service
metadata:
  name: api-db-service
spec:
  selector:
    app: api-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306