stages:
  - website_build-and-test
  - app_build-and-test
  - app_deploy
  - openapi_gen
  - openapi_deploy

build_website:
  stage: website_build-and-test
  image: node:14-alpine
  tags:
    - docker
  script:
    - cd WebApp/tourguide
    - npm config set @here:registry https://repo.platform.here.com/artifactory/api/npm/maps-api-for-javascript/
    - npm install --prefer-offline --no-audit
    - npm run build:prod
  artifacts:
    name: "website"
    paths:
      - WebApp/tourguide/dist/tourguide

lint_format_test_website:
  stage: website_build-and-test
  image: buildkite/puppeteer
  tags:
    - docker
  script:
    - cd WebApp/tourguide
    - npm config set @here:registry https://repo.platform.here.com/artifactory/api/npm/maps-api-for-javascript/
    - npm install --prefer-offline --no-audit
    - npm run lint
    - npm run prettier:check
    - npm run test:ci
  artifacts:
    name: "test-and-coverage"
    reports:
      junit:
        - WebApp/tourguide/artifacts/tests/junit-test-results.xml
      cobertura:
        - WebApp/tourguide/coverage/tourguide/cobertura-coverage.xml


app_lintDebug:
  image: jangrewe/gitlab-ci-android
  stage: app_build-and-test
  before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - cd ./Frontend/App/DigitalTourGuide/
    - chmod +x ./gradlew
  script:
  - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

app_build:
  image: jangrewe/gitlab-ci-android
  stage: app_build-and-test
  before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - cd ./Frontend/App/DigitalTourGuide/
    - chmod +x ./gradlew
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - ./Frontend/App/DigitalTourGuide/app/build/outputs/apk

app_testDebug:
  image: jangrewe/gitlab-ci-android
  stage: app_build-and-test
  before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - cd ./Frontend/App/DigitalTourGuide/
    - chmod +x ./gradlew
  script:
  - ./gradlew -Pci --console=plain :app:testDebug

app_apk_deploy:
  stage: app_deploy
  before_script:
    - apk update
    - apk add git 
    - apk add --update openssl
  script:
    - cp -r Frontend/App/DigitalTourGuide/app/build/outputs/apk Documents/App
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git pull .
    - git add Documents/App
    - git commit -m "App APK updated" || if [ $? -eq 64 ]; then echo "success"; else echo $code; fi
    - git push https://${GITLAB_USER_LOGIN}:${TOKEN}@gitlab.lrz.de/swe2_ss2021/Gruppe02.git/ HEAD:develop -f
  only:
    refs:
      - develop
  except:
    changes: 
      - Documents/App/

openapi_gen:
  image: jeshan/swagger-codegen-cli
  stage: openapi_gen
  before_script:
    - apk update
    - apk add --update openssl
    - wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.1.0/openapi-generator-cli-5.1.0.jar -O openapi-generator-cli.jar
  script:
    - 'java -jar openapi-generator-cli.jar generate -g kotlin -i Documents/ApiSpec/openapi.yaml -o openapi-kotlin-client'
  only:
    refs:
      - develop
    changes: 
      - Documents/ApiSpec/openapi.yaml
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths: ['openapi-kotlin-client']

openapi_deploy:
  stage: openapi_deploy
  before_script:
    - apk update
    - apk add git 
    - apk add --update openssl
  script:
    - rm -r Frontend/App/DigitalTourGuide/app/src/main/java/edu/hm/digitaltourguide/api
    - mv openapi-kotlin-client/src/main/kotlin/org/openapitools/client Frontend/App/DigitalTourGuide/app/src/main/java/edu/hm/digitaltourguide/api
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git pull .
    - git add Frontend/App/DigitalTourGuide/app/src/main/java/edu/hm/digitaltourguide/api
    - git commit -m "Updated API Client" || if [ $? -eq 64 ]; then echo "success"; else echo $code; fi
    - git push https://${GITLAB_USER_LOGIN}:${TOKEN}@gitlab.lrz.de/swe2_ss2021/Gruppe02.git/ HEAD:develop -f
  only:
    refs:
      - develop
    changes: 
      - Documents/ApiSpec/openapi.yaml
