stages:
    - install
    - build

install_dependencies_website:
    stage: install
    image: node:14-alpine
    tags:
        - docker
    script:
        - cd WebApp/tourguide
        - npm config set @here:registry https://repo.platform.here.com/artifactory/api/npm/maps-api-for-javascript/
        - npm install --prefer-offline --no-audit
    cache:
        key:
            files:
                - WebApp/tourguide/package-lock.json
        paths:
            - WebApp/tourguide/node_modules

build_website:
    stage: build
    image: node:14-alpine
    tags:
        - docker
    script:
        - cd WebApp/tourguide
        - npm run ng build --prod
    artifacts:
        name: "website"
        paths:
            - WebApp/tourguide/dist/tourguide
    cache:
        key:
            files:
                - WebApp/tourguide/package-lock.json
        paths:
            - WebApp/tourguide/node_modules
        policy: pull

