stages:
    - install

install_dependencies:
    stage: install
    image: node:14-alpine
    tags:
        - docker
    script:
        - npm ci
    cache:
        key:
            files:
                - package-lock.json
        paths:
            - node_modules

