stages:
    - install

variables:
    - WEBSITE-PATH: "WebApp/tourguide"

install_dependencies_website:
    stage: install
    image: node:14-alpine
    tags:
        - docker
    script:
        - cd $WEBSITE-PATH
        - npm ci
    cache:
        key:
            files:
                - $WEBSITE-PATH/package-lock.json
        paths:
            - $WEBSITE-PATH/node_modules

