stages:
    - install

install_dependencies_website:
    stage: install
    image: node:14-alpine
    tags:
        - docker
    script:
        - cd WebApp/tourguide
        - npm ci
    cache:
        key:
            files:
                - WebApp/tourguide/package-lock.json
        paths:
            - WebApp/tourguide/node_modules

