stages:
  - install
  - build-and-test

.website_cache: &website_cache
  key:
    files:
      - WebApp/tourguide/package-lock.json
  paths:
    - WebApp/tourguide/node_modules
  policy: pull

website_install_dependencies:
  stage: install
  image: node:14-alpine
  tags:
    - docker
  script:
    - cd WebApp/tourguide
    - npm config set @here:registry https://repo.platform.here.com/artifactory/api/npm/maps-api-for-javascript/
    - npm install --prefer-offline --no-audit
  cache:
    key:
      files:
        - WebApp/tourguide/package-lock.json
    paths:
      - WebApp/tourguide/node_modules
  only:
    changes:
      - WebApp/tourguide/package-lock.json

website_build:
  stage: build-and-test
  image: node:14-alpine
  tags:
    - docker
  script:
    - cd WebApp/tourguide
    - npm run build:prod
  artifacts:
    name: "website"
    paths:
      - WebApp/tourguide/dist/tourguide
  cache:
    <<: *website_cache

website_lint:
  stage: build-and-test
  image: node:14-alpine
  tags:
    - docker
  script:
    - cd WebApp/tourguide
    - npm run lint
  cache:
    <<: *website_cache

website_prettier:
  stage: build-and-test
  image: node:14-alpine
  tags:
    - docker
  script:
    - cd WebApp/tourguide
    - npm run prettier:check
  cache:
    <<: *website_cache

website_test:
  stage: build-and-test
  image: buildkite/puppeteer
  tags:
    - docker
  script:
    - cd WebApp/tourguide
    - npm run test:ci
  artifacts:
    name: "test-and-coverage"
    reports:
      junit:
        - WebApp/tourguide/artifacts/tests/junit-test-results.xml
      cobertura:
        - WebApp/tourguide/coverage/tourguide/cobertura-coverage.xml
  cache:
    <<: *website_cache
