apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-k8s-test-deployment
  labels:
    app: gitlab-k8s-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-k8s-test
  template:
    metadata:
      labels:
        app: gitlab-k8s-test
    spec:
      containers:
      - name: gitlab-k8s-test
        image: gitlab.lrz.de:5005/swe2_ss2021/gruppe02/website:105-deployment-einrichten
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: image-pull-secret

---

apiVersion: v1
kind: Service
metadata:
  name: gitlab-k8s-test-service
spec:
  selector:
    app: gitlab-k8s-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab-k8s-test-ingress
  annotations:
    cert-manager.io/cluster-issuer: http-fh-issuer
    kubernetes.io/ingress.class: "public"
spec:
  tls:
  - hosts:
    - test.sart.solutions
    secretName: gitlab-k8s-test-certificate-tls
  rules:
  - host: test.sart.solutions
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitlab-k8s-test-service
            port:
              number: 80