/*
 * Digitaler Reiseführer
 *
 * REST Api für den digitalen Reiseführer.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class PointOfInterestApiController : ControllerBase
    { 
        /// <summary>
        /// Add a new poi to the database
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        /// <response code="400">Invalid input</response>
        [HttpPost]
        [Route("/v2/pointOfInterest")]
        [ValidateModelState]
        [SwaggerOperation("AddPOI")]
        [SwaggerResponse(statusCode: 200, type: typeof(PointOfInterest), description: "Success")]
        public virtual IActionResult AddPOI([FromBody]PostPointOfInterest body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(PointOfInterest));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);
            string exampleJson = null;
            exampleJson = "{\n  \"latitude\" : 0.8008281904610115,\n  \"averageRating\" : 1.4658129805029452,\n  \"name\" : \"name\",\n  \"numberOfRatings\" : 5,\n  \"description\" : \"description\",\n  \"id\" : \"id\",\n  \"longitude\" : 6.027456183070403\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<PointOfInterest>(exampleJson)
                        : default(PointOfInterest);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Deletes the poi to a given id
        /// </summary>
        /// <param name="poiID"></param>
        /// <response code="200">Success</response>
        /// <response code="404">Not found</response>
        [HttpDelete]
        [Route("/v2/pointOfInterest/{poiID}")]
        [ValidateModelState]
        [SwaggerOperation("DeletePOI")]
        public virtual IActionResult DeletePOI([FromRoute][Required]string poiID)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Get the center of all poi&#x27;s from the given user
        /// </summary>
        /// <param name="userName"></param>
        /// <response code="200">Success</response>
        /// <response code="404">User not found</response>
        [HttpGet]
        [Route("/v2/pointOfInterest/{userName}/center")]
        [ValidateModelState]
        [SwaggerOperation("GetCenterOfPOIs")]
        [SwaggerResponse(statusCode: 200, type: typeof(InlineResponse200), description: "Success")]
        public virtual IActionResult GetCenterOfPOIs([FromRoute][Required]string userName)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(InlineResponse200));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);
            string exampleJson = null;
            exampleJson = "{\n  \"latitude\" : 0.8008281904610115,\n  \"longitude\" : 6.027456183070403\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<InlineResponse200>(exampleJson)
                        : default(InlineResponse200);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Gets the poi to a given id
        /// </summary>
        /// <param name="poiID"></param>
        /// <response code="200">Success</response>
        /// <response code="404">Not found</response>
        [HttpGet]
        [Route("/v2/pointOfInterest/{poiID}")]
        [ValidateModelState]
        [SwaggerOperation("GetPOI")]
        [SwaggerResponse(statusCode: 200, type: typeof(PointOfInterest), description: "Success")]
        public virtual IActionResult GetPOI([FromRoute][Required]string poiID)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(PointOfInterest));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);
            string exampleJson = null;
            exampleJson = "{\n  \"latitude\" : 0.8008281904610115,\n  \"averageRating\" : 1.4658129805029452,\n  \"name\" : \"name\",\n  \"numberOfRatings\" : 5,\n  \"description\" : \"description\",\n  \"id\" : \"id\",\n  \"longitude\" : 6.027456183070403\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<PointOfInterest>(exampleJson)
                        : default(PointOfInterest);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Get all poi&#x27;s from the given user
        /// </summary>
        /// <param name="userName"></param>
        /// <response code="200">Success</response>
        /// <response code="404">User not found</response>
        [HttpGet]
        [Route("/v2/pointOfInterest/{userName}")]
        [ValidateModelState]
        [SwaggerOperation("GetPOIs")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<string>), description: "Success")]
        public virtual IActionResult GetPOIs([FromRoute][Required]string userName)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<string>));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);
            string exampleJson = null;
            exampleJson = "[ \"\", \"\" ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<List<string>>(exampleJson)
                        : default(List<string>);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Edits the poi to a given id
        /// </summary>
        /// <param name="body"></param>
        /// <param name="poiID"></param>
        /// <response code="200">Success</response>
        /// <response code="400">Invalid input</response>
        /// <response code="404">Not found</response>
        [HttpPut]
        [Route("/v2/pointOfInterest/{poiID}")]
        [ValidateModelState]
        [SwaggerOperation("PutPOI")]
        [SwaggerResponse(statusCode: 200, type: typeof(PointOfInterest), description: "Success")]
        public virtual IActionResult PutPOI([FromBody]PostPointOfInterest body, [FromRoute][Required]string poiID)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(PointOfInterest));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);
            string exampleJson = null;
            exampleJson = "{\n  \"latitude\" : 0.8008281904610115,\n  \"averageRating\" : 1.4658129805029452,\n  \"name\" : \"name\",\n  \"numberOfRatings\" : 5,\n  \"description\" : \"description\",\n  \"id\" : \"id\",\n  \"longitude\" : 6.027456183070403\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<PointOfInterest>(exampleJson)
                        : default(PointOfInterest);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
