/*
 * Digitaler Reiseführer
 *
 * REST Api für den digitalen Reiseführer.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class PromotedApiController : ControllerBase
    { 
        /// <summary>
        /// Get all promoted pois in an area
        /// </summary>
        /// <param name="longitudeMin"></param>
        /// <param name="latitudeMin"></param>
        /// <param name="longitudeMax"></param>
        /// <param name="latitudeMax"></param>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/v2/promoted")]
        [ValidateModelState]
        [SwaggerOperation("GetPromotedPOIs")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<string>), description: "Success")]
        public virtual IActionResult GetPromotedPOIs([FromQuery][Required()]decimal? longitudeMin, [FromQuery][Required()]decimal? latitudeMin, [FromQuery][Required()]decimal? longitudeMax, [FromQuery][Required()]decimal? latitudeMax)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<string>));
            string exampleJson = null;
            exampleJson = "[ \"\", \"\" ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<List<string>>(exampleJson)
                        : default(List<string>);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
