/**
 * API
 * API Spec f�r den digitalen Reisef�hrer
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PointOfInterest } from './pointOfInterest';


export interface PoIReview { 
    /**
     * Gets or Sets poIReviewId
     */
    poIReviewId: string;
    pointOfInterest: PointOfInterest;
    /**
     * Gets or Sets Content
     */
    content: string;
    /**
     * Gets or Sets Rating
     */
    rating: number;
    /**
     * Gets or Sets username
     */
    userName: string;
}

