/**
 * Digitaler Reiseführer
 * REST Api für den digitalen Reiseführer.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostPointOfInterest { 
    id?: number;
    name: string;
    description: string;
    latitude: number;
    longitude: number;
    averageRating: number;
    numberOfRatings: number;
}

