/**
 * API
 * API Spec f�r den digitalen Reisef�hrer
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Gets or Sets Role
 */
export type Role = 'content-creator' | 'moderator' | 'admin' | 'promoter';

export const Role = {
    ContentCreator: 'content-creator' as Role,
    Moderator: 'moderator' as Role,
    Admin: 'admin' as Role,
    Promoter: 'promoter' as Role
};

