/**
 * API
 * API Spec f�r den digitalen Reisef�hrer
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Route } from './route';


export interface RouteReview { 
    /**
     * Gets or Sets RouteReviewId
     */
    routeReviewId: string;
    route: Route;
    /**
     * Gets or Sets Content
     */
    content: string;
    /**
     * Gets or Sets Rating
     */
    rating: number;
    /**
     * Gets or Sets username
     */
    userName: string;
}

