apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  annotations:
    app.gitlab.com/app: __CI_PROJECT_PATH_SLUG__
    app.gitlab.com/env: __CI_ENVIRONMENT_SLUG__
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
      annotations:
        app.gitlab.com/app: __CI_PROJECT_PATH_SLUG__
        app.gitlab.com/env: __CI_ENVIRONMENT_SLUG__
    spec:
      containers:
      - name: keycloak
        image: gitlab.lrz.de:5005/swe2_ss2021/gruppe02/keycloak:__CI_COMMIT_SHA__
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: image-pull-secret

---

apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  annotations:
    cert-manager.io/cluster-issuer: http-fh-issuer
    kubernetes.io/ingress.class: "public"
spec:
  tls:
  - hosts:
    - __URL__
    secretName: tls-certificate
  rules:
  - host: __URL__
    http:
      paths:
      - path: /auth/
        pathType: Prefix
        backend:
          service:
            name: keycloak-service
            port:
              number: 80