/**
* Digitaler Reiseführer
* REST Api für den digitalen Reiseführer.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package edu.hm.digitaltourguide.api.models


import com.squareup.moshi.Json

/**
 * 
 * @param latitude 
 * @param longitude 
 */

data class InlineResponse200 (
    @Json(name = "latitude")
    val latitude: java.math.BigDecimal? = null,
    @Json(name = "longitude")
    val longitude: java.math.BigDecimal? = null
)

