/**
* API
* API Spec f�r den digitalen Reisef�hrer
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package edu.hm.digitaltourguide.api.models


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize


/**
 * Model class for a PointOfInterest
 * @param poIID Gets or Sets Id
 * @param name Gets or Sets Name
 * @param userName Gets or Sets username
 * @param description Gets or Sets Description
 * @param latitude Gets or Sets Latitude
 * @param longitude Gets or Sets Longitude
 * @param averageRating Gets or Sets AverageRating
 * @param numberOfRatings Gets or Sets NumberOfRatings
 * @param imageUrl Gets or Sets ImageUrl
 * @param isPromoted Defines, whether this poi is promoted or not
 */
@Parcelize

data class PointOfInterest (
    /* Gets or Sets Id */
    @Json(name = "poIID")
    val poIID: java.util.UUID,
    /* Gets or Sets Name */
    @Json(name = "name")
    val name: kotlin.String,
    /* Gets or Sets username */
    @Json(name = "userName")
    val userName: kotlin.String,
    /* Gets or Sets Description */
    @Json(name = "description")
    val description: kotlin.String,
    /* Gets or Sets Latitude */
    @Json(name = "latitude")
    val latitude: kotlin.Double,
    /* Gets or Sets Longitude */
    @Json(name = "longitude")
    val longitude: kotlin.Double,
    /* Gets or Sets AverageRating */
    @Json(name = "averageRating")
    val averageRating: kotlin.Double,
    /* Gets or Sets NumberOfRatings */
    @Json(name = "numberOfRatings")
    val numberOfRatings: kotlin.Int,
    /* Gets or Sets ImageUrl */
    @Json(name = "imageUrl")
    val imageUrl: kotlin.String,
    /* Defines, whether this poi is promoted or not */
    @Json(name = "isPromoted")
    val isPromoted: kotlin.Boolean
) : Parcelable

