/**
* Digitaler Reiseführer
* REST Api für den digitalen Reiseführer.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param name 
 * @param description 
 * @param latitude 
 * @param longitude 
 * @param averageRating 
 * @param numberOfRatings 
 * @param imageURL 
 */

data class PointOfInterest (
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "name")
    val name: kotlin.String,
    @Json(name = "description")
    val description: kotlin.String,
    @Json(name = "latitude")
    val latitude: java.math.BigDecimal,
    @Json(name = "longitude")
    val longitude: java.math.BigDecimal,
    @Json(name = "averageRating")
    val averageRating: java.math.BigDecimal,
    @Json(name = "numberOfRatings")
    val numberOfRatings: kotlin.Int,
    @Json(name = "imageURL")
    val imageURL: kotlin.String
)

