/**
* API
* API Spec f�r den digitalen Reisef�hrer
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package edu.hm.digitaltourguide.api.models


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize


/**
 * 
 * @param poIID Gets or Sets Id
 * @param content Gets or Sets Content
 * @param rating Gets or Sets Rating
 * @param userName Gets or Sets username
 */
@Parcelize

data class PostPoIReview (
    /* Gets or Sets Id */
    @Json(name = "poIID")
    val poIID: java.util.UUID,
    /* Gets or Sets Content */
    @Json(name = "content")
    val content: kotlin.String,
    /* Gets or Sets Rating */
    @Json(name = "rating")
    val rating: kotlin.Int,
    /* Gets or Sets username */
    @Json(name = "userName")
    val userName: kotlin.String
) : Parcelable

