/**
 * Digitaler Reiseführer
 * REST Api für den digitalen Reiseführer.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package edu.hm.digitaltourguide.api.models


/**
 * 
 * @param id
 * @param name
 * @param description 
 * @param latitude 
 * @param longitude 
 * @param averageRating
 * @param numberOfRatings
 * @param imageURL
 */
data class PostPointOfInterest (

    val id: String? = null,
    val name: String,
    val description: String,
    val latitude: java.math.BigDecimal,
    val longitude: java.math.BigDecimal,
    val averageRating: java.math.BigDecimal,
    val numberOfRatings: Int,
    val imageURL: kotlin.String,
) {
}