/**
 * Digitaler Reiseführer
 * REST Api für den digitalen Reiseführer.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package edu.hm.digitaltourguide.api.models


/**
 * 
 * @param content 
 * @param rating 
 * @param userName 
 */
data class Review (

    val content: String,
    val rating: Float,
    val userName: String
) {
}