/**
* API
* API Spec fuer den digitalen Reisefuehrer
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package edu.hm.digitaltourguide.api.models

import edu.hm.digitaltourguide.api.models.Role

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize


/**
 * 
 * @param creatorName Gets or Sets CreatorName
 * @param requestedRole 
 */
@Parcelize

data class RoleModel (
    /* Gets or Sets CreatorName */
    @Json(name = "creatorName")
    val creatorName: kotlin.String,
    @Json(name = "requestedRole")
    val requestedRole: Role
) : Parcelable

