/**
 * Digitaler Reiseführer
 * REST Api für den digitalen Reiseführer.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package edu.hm.digitaltourguide.api.models

import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param pointOfInterests 
 * @param name 
 * @param description 
 * @param creatorName 
 * @param duration 
 * @param polyline
 * @param imageURL
 */
data class Route (
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "pointOfInterests")
    val pointOfInterests: kotlin.collections.List<PointOfInterest>,
    @Json(name = "name")
    val name: kotlin.String,
    @Json(name = "description")
    val description: kotlin.String,
    @Json(name = "creatorName")
    val creatorName: kotlin.String,
    @Json(name = "duration")
    val duration: kotlin.Float,
    @Json(name = "polyline")
    val polyline: kotlin.String,
    @Json(name = "imageURL")
    val imageURL: kotlin.String
)

