/**
* API
* API Spec f�r den digitalen Reisef�hrer
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package edu.hm.digitaltourguide.api.models

import edu.hm.digitaltourguide.api.models.Route

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize


/**
 * 
 * @param routeReviewId Gets or Sets RouteReviewId
 * @param route 
 * @param content Gets or Sets Content
 * @param rating Gets or Sets Rating
 * @param userName Gets or Sets username
 */
@Parcelize

data class RouteReview (
    /* Gets or Sets RouteReviewId */
    @Json(name = "routeReviewId")
    val routeReviewId: java.util.UUID,
    @Json(name = "route")
    val route: Route,
    /* Gets or Sets Content */
    @Json(name = "content")
    val content: kotlin.String,
    /* Gets or Sets Rating */
    @Json(name = "rating")
    val rating: kotlin.Int,
    /* Gets or Sets username */
    @Json(name = "userName")
    val userName: kotlin.String
) : Parcelable

