/**
* Digitaler Reiseführer
* REST Api für den digitalen Reiseführer.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param userName 
 * @param role 
 */

data class User (
    @Json(name = "userName")
    val userName: kotlin.String,
    @Json(name = "role")
    val role: User.Role
) {

    /**
     * 
     * Values: contentCreator,admin,moderator,tourist,advertiser
     */
    enum class Role(val value: kotlin.String) {
        @Json(name = "ContentCreator") contentCreator("ContentCreator"),
        @Json(name = "Admin") admin("Admin"),
        @Json(name = "Moderator") moderator("Moderator"),
        @Json(name = "Tourist") tourist("Tourist"),
        @Json(name = "Advertiser") advertiser("Advertiser");
    }
}

