/**
 * Digitaler Reiseführer
 * REST Api für den digitalen Reiseführer.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package edu.hm.digitaltourguide.api.models


/**
 * 
 * @param userName 
 * @param role 
 */
data class User (

    val userName: String,
    val role: Role
) {
    /**
    * 
    * Values: CONTENTCREATOR,ADMIN,MODERATOR,TOURIST,ADVERTISER
    */
    enum class Role(val value: String){
        CONTENTCREATOR("ContentCreator"),
        ADMIN("Admin"),
        MODERATOR("Moderator"),
        TOURIST("Tourist"),
        ADVERTISER("Advertiser");
    }
}