{
  "openapi": "3.0.1",
  "info": {
    "title": "API",
    "version": "v1"
  },
  "paths": {
    "/Healthcheck": {
      "get": {
        "tags": [
          "Healthcheck"
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/pointOfInterest": {
      "post": {
        "tags": [
          "PointOfInterest"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PostPointOfInterest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/PostPointOfInterest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/PostPointOfInterest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "put": {
        "tags": [
          "PointOfInterest"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PutPointOfInterest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/PutPointOfInterest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/PutPointOfInterest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/pointOfInterest/{poiID}": {
      "delete": {
        "tags": [
          "PointOfInterest"
        ],
        "parameters": [
          {
            "name": "poiID",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "get": {
        "tags": [
          "PointOfInterest"
        ],
        "parameters": [
          {
            "name": "poiID",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/pointOfInterest/getUserPoIs/{userName}": {
      "get": {
        "tags": [
          "PointOfInterest"
        ],
        "parameters": [
          {
            "name": "userName",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/route": {
      "post": {
        "tags": [
          "Route"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PostRoute"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/PostRoute"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/PostRoute"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "put": {
        "tags": [
          "Route"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PutRoute"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/PutRoute"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/PutRoute"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/route/{routeID}": {
      "delete": {
        "tags": [
          "Route"
        ],
        "parameters": [
          {
            "name": "routeID",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "get": {
        "tags": [
          "Route"
        ],
        "parameters": [
          {
            "name": "routeID",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/routes/{creatorName}": {
      "get": {
        "tags": [
          "Route"
        ],
        "parameters": [
          {
            "name": "creatorName",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "PostPointOfInterest": {
        "required": [
          "description",
          "imageUrl",
          "latitude",
          "longitude",
          "name"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "nullable": true
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "latitude": {
            "type": "number",
            "format": "double"
          },
          "longitude": {
            "type": "number",
            "format": "double"
          },
          "imageUrl": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "PutPointOfInterest": {
        "required": [
          "description",
          "id",
          "imageUrl",
          "latitude",
          "longitude",
          "name"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "latitude": {
            "type": "number",
            "format": "double"
          },
          "longitude": {
            "type": "number",
            "format": "double"
          },
          "imageUrl": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "PostRoute": {
        "required": [
          "creatorName",
          "description",
          "duration",
          "name",
          "pointOfInterests",
          "polyline"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "nullable": true
          },
          "pointOfInterests": {
            "type": "array",
            "items": {
              "type": "string",
              "format": "uuid"
            }
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "creatorName": {
            "type": "string"
          },
          "duration": {
            "type": "number",
            "format": "float"
          },
          "polyline": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "PutRoute": {
        "required": [
          "creatorName",
          "description",
          "duration",
          "id",
          "name",
          "pointOfInterests",
          "polyline"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "pointOfInterests": {
            "type": "array",
            "items": {
              "type": "string",
              "format": "uuid"
            }
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "creatorName": {
            "type": "string"
          },
          "duration": {
            "type": "number",
            "format": "float"
          },
          "polyline": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    }
  }
}