{
  "openapi": "3.0.1",
  "info": {
    "title": "API",
    "description": "API Spec für den digitalen Reiseführer",
    "version": "v1"
  },
  "paths": {
    "/Healthcheck": {
      "get": {
        "tags": [
          "Healthcheck"
        ],
        "summary": "Return 200 ok.",
        "operationId": "Healthcheck",
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/pointOfInterest": {
      "post": {
        "tags": [
          "PointOfInterest"
        ],
        "summary": "Add a new poi to the database",
        "operationId": "AddPOIAsync",
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PostPointOfInterest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/PostPointOfInterest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/PostPointOfInterest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Invalid input"
          }
        }
      },
      "put": {
        "tags": [
          "PointOfInterest"
        ],
        "summary": "Edits the poi to a given id",
        "operationId": "PutPOIAsync",
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PutPointOfInterest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/PutPointOfInterest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/PutPointOfInterest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Invalid input"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    },
    "/api/pointOfInterest/{poiID}": {
      "delete": {
        "tags": [
          "PointOfInterest"
        ],
        "summary": "Deletes the poi to a given id",
        "operationId": "DeletePOIAsync",
        "parameters": [
          {
            "name": "poiID",
            "in": "path",
            "description": "the poiID to delete",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "404": {
            "description": "Not found"
          }
        }
      },
      "get": {
        "tags": [
          "PointOfInterest"
        ],
        "summary": "Gets the poi to a given id",
        "operationId": "GetPOIAsync",
        "parameters": [
          {
            "name": "poiID",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    },
    "/api/pointOfInterest/getUserPoIs/{userName}": {
      "get": {
        "tags": [
          "PointOfInterest"
        ],
        "summary": "Get all poi's from the given user",
        "operationId": "GetPOIsAsync",
        "parameters": [
          {
            "name": "userName",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "404": {
            "description": "User not found"
          }
        }
      }
    },
    "/api/route": {
      "post": {
        "tags": [
          "Route"
        ],
        "summary": "Add a new route to the database",
        "operationId": "AddRouteAsync",
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PostRoute"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/PostRoute"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/PostRoute"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Invalid input"
          },
          "404": {
            "description": "Given poi does not exist"
          }
        }
      },
      "put": {
        "tags": [
          "Route"
        ],
        "summary": "Edits the route to a given id",
        "operationId": "PutRoute",
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PutRoute"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/PutRoute"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/PutRoute"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Invalid input"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    },
    "/api/route/{routeID}": {
      "delete": {
        "tags": [
          "Route"
        ],
        "summary": "Deletes the route to a given id",
        "operationId": "DeleteRoute",
        "parameters": [
          {
            "name": "routeID",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "404": {
            "description": "Not found"
          }
        }
      },
      "get": {
        "tags": [
          "Route"
        ],
        "summary": "Gets the route to a given id",
        "operationId": "GetRoute",
        "parameters": [
          {
            "name": "routeID",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    },
    "/api/routes/{creatorName}": {
      "get": {
        "tags": [
          "Route"
        ],
        "summary": "Get all routes from the given user",
        "operationId": "GetRoutes",
        "parameters": [
          {
            "name": "creatorName",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "404": {
            "description": "User not found"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "PostPointOfInterest": {
        "required": [
          "description",
          "imageUrl",
          "latitude",
          "longitude",
          "name"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "Gets or Sets Id",
            "nullable": true
          },
          "name": {
            "type": "string",
            "description": "Gets or Sets Name"
          },
          "description": {
            "type": "string",
            "description": "Gets or Sets Description"
          },
          "latitude": {
            "type": "number",
            "description": "Gets or Sets Latitude",
            "format": "double"
          },
          "longitude": {
            "type": "number",
            "description": "Gets or Sets Longitude",
            "format": "double"
          },
          "imageUrl": {
            "type": "string",
            "description": "Gets or Sets ImageUrl"
          }
        },
        "additionalProperties": false,
        "description": "Model class for posting a new poi"
      },
      "PostRoute": {
        "required": [
          "creatorName",
          "description",
          "duration",
          "name",
          "pointOfInterests",
          "polyline"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "Gets or Sets Id",
            "nullable": true
          },
          "pointOfInterests": {
            "type": "array",
            "items": {
              "type": "string",
              "format": "uuid"
            },
            "description": "Gets or Sets PointOfInterests"
          },
          "name": {
            "type": "string",
            "description": "Gets or Sets Name"
          },
          "description": {
            "type": "string",
            "description": "Gets or Sets Description"
          },
          "creatorName": {
            "type": "string",
            "description": "Gets or Sets CreatorName"
          },
          "duration": {
            "type": "number",
            "description": "Gets or Sets Duration",
            "format": "float"
          },
          "polyline": {
            "type": "string",
            "description": "Gets or Sets Polyline"
          }
        },
        "additionalProperties": false
      },
      "PutPointOfInterest": {
        "required": [
          "description",
          "id",
          "imageUrl",
          "latitude",
          "longitude",
          "name"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "Gets or Sets Id"
          },
          "name": {
            "type": "string",
            "description": "Gets or Sets Name"
          },
          "description": {
            "type": "string",
            "description": "Gets or Sets Description"
          },
          "latitude": {
            "type": "number",
            "description": "Gets or Sets Latitude",
            "format": "double"
          },
          "longitude": {
            "type": "number",
            "description": "Gets or Sets Longitude",
            "format": "double"
          },
          "imageUrl": {
            "type": "string",
            "description": "Gets or Sets ImageUrl"
          }
        },
        "additionalProperties": false
      },
      "PutRoute": {
        "required": [
          "creatorName",
          "description",
          "duration",
          "id",
          "name",
          "pointOfInterests",
          "polyline"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "Gets or Sets Id"
          },
          "pointOfInterests": {
            "type": "array",
            "items": {
              "type": "string",
              "format": "uuid"
            },
            "description": "Gets or Sets PointOfInterests"
          },
          "name": {
            "type": "string",
            "description": "Gets or Sets Name"
          },
          "description": {
            "type": "string",
            "description": "Gets or Sets Description"
          },
          "creatorName": {
            "type": "string",
            "description": "Gets or Sets CreatorName"
          },
          "duration": {
            "type": "number",
            "description": "Gets or Sets Duration",
            "format": "float"
          },
          "polyline": {
            "type": "string",
            "description": "Gets or Sets Polyline"
          }
        },
        "additionalProperties": false
      }
    }
  }
}