/**
 * API
 * API Spec für den digitalen Reiseführer
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface HealthcheckServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Return 200 ok.
     * 
     */
    healthcheck(extraHttpRequestParams?: any): Observable<{}>;

}
