/**
 * API
 * API Spec f�r den digitalen Reisef�hrer
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PoIReview } from '../model/models';
import { PostPoIReview } from '../model/models';
import { ProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PoIReviewServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Add a new review for a poi
     * 
     * @param postPoIReview 
     */
    addPoIReview(postPoIReview: PostPoIReview, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Deletes the given review.
     * 
     * @param poiId The id from the review to delete
     */
    deletePoIReview(poiId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Gets all reviews for the given poi
     * 
     * @param poiId The id from the poi
     */
    getPoIReviews(poiId: string, extraHttpRequestParams?: any): Observable<Array<PoIReview>>;

}
