/**
 * Digitaler Reiseführer
 * REST Api für den digitalen Reiseführer.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PostRoute } from '../model/models';
import { Route } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RouteServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Add a new route to the database
     * 
     * @param route 
     */
    addRoute(route: PostRoute, extraHttpRequestParams?: any): Observable<Route>;

    /**
     * Deletes the route to a given id
     * 
     * @param routeID 
     */
    deleteRoute(routeID: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Gets the route to a given id
     * 
     * @param routeID 
     */
    getRoute(routeID: string, extraHttpRequestParams?: any): Observable<Route>;

    /**
     * Get all routes from the given user
     * 
     * @param userName 
     */
    getRoutes(userName: string, extraHttpRequestParams?: any): Observable<Array<number>>;

    /**
     * Edits the route to a given id
     * 
     * @param routeID 
     * @param route 
     */
    putRoute(routeID: string, route: PostRoute, extraHttpRequestParams?: any): Observable<{}>;

}
