/**
 * API
 * API Spec für den digitalen Reiseführer
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PostRoute } from '../model/models';
import { ProblemDetails } from '../model/models';
import { PutRoute } from '../model/models';
import { Route } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RouteServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Add a new route to the database
     * 
     * @param postRoute 
     */
    addRoute(postRoute: PostRoute, extraHttpRequestParams?: any): Observable<Route>;

    /**
     * Deletes the route to a given id
     * 
     * @param routeID 
     */
    deleteRoute(routeID: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Gets the route to a given id
     * 
     * @param routeID 
     */
    getRoute(routeID: string, extraHttpRequestParams?: any): Observable<Route>;

    /**
     * Get all routes from the given user
     * 
     * @param creatorName 
     */
    getRoutes(creatorName: string, extraHttpRequestParams?: any): Observable<Array<Route>>;

    /**
     * Edits the route to a given id
     * 
     * @param putRoute 
     */
    putRoute(putRoute: PutRoute, extraHttpRequestParams?: any): Observable<{}>;

}
