/**
 * API
 * API Spec f�r den digitalen Reisef�hrer
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProblemDetails } from '../model/models';
import { RoleModel } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface VerificationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Accept the role request of a specific user
     * 
     * @param userName 
     */
    acceptRequest(userName: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Reject the role request of a specific user
     * 
     * @param userName 
     */
    denyRequest(userName: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Fetch all open role requests
     * 
     */
    getRequests(extraHttpRequestParams?: any): Observable<Array<RoleModel>>;

    /**
     * Add a new role request
     * 
     * @param roleModel 
     */
    requestRole(roleModel: RoleModel, extraHttpRequestParams?: any): Observable<{}>;

}
